stages:
  - setup
  - validation
#  - unit_testing
  - analyze_sample_apps
  - release

# The pipeline covers a series of triggers to ensure full testing and coverage

workflow:
  rules:
    - when: always

# Debug Stage
debug_merge_request:
  stage: setup
  script:
    - echo "Basic Merge Request Variables..." 
    - echo "CI_MERGE_REQUEST_IID is '$CI_MERGE_REQUEST_IID'"
    - echo "CI_MERGE_REQUEST_SOURCE_BRANCH_NAME is $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
    - echo "CI_MERGE_REQUEST_TARGET_BRANCH_NAME is $CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - echo "CI_MERGE_REQUEST_EVENT_TYPE is $CI_MERGE_REQUEST_EVENT_TYPE"
    
    - echo "Commit Information Variables..."
    - echo "CI_COMMIT_REF_NAME is $CI_COMMIT_REF_NAME"
    - echo "CI_COMMIT_BRANCH is $CI_COMMIT_BRANCH"
    - echo "CI_COMMIT_MESSAGE is $CI_COMMIT_MESSAGE" 

    - echo "Determining branch name..."
    - BRANCH_NAME=${CI_COMMIT_BRANCH:-${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$CI_COMMIT_REF_NAME}}
    - echo "Branch name determined $BRANCH_NAME"

    - echo "Pipeline Metadata..."
    - echo "CI_PIPELINE_SOURCE is $CI_PIPELINE_SOURCE"
  rules:
    - changes:
        - firebase-dart-admin-auth-sdk/backend/**/*
        - firebase-dart-admin-auth-sdk/docs/**/*
        - firebase-dart-admin-auth-sdk/example/**/*
        - tools/**/*
        - "*"
        - "**/*"
      when: always
    - when: never

# Validation Conditional Triggers for Docs
validation_trigger_docs:
  stage: validation
  trigger:
    include: tools/pipelines/firebase-hosting/child-ci-production-docs.yml
  rules:
    - changes:
        - firebase-dart-admin-auth-sdk/docs/**/*
      when: always
    - when: never

# # Unit Test Conditional Triggers
# unit_test_trigger:
#   stage: unit_testing
#   trigger:
#     include: tools/pipelines/backend/child-ci-unit-tests.yml
#   needs:
#     - job: validation_trigger
#   rules:
#     # Always runs after validation trigger
#     - when: always
    
# Sample App Conditional Triggers
analyze_flutter_web:
  stage: analyze_sample_apps
  trigger:
    include: tools/pipelines/frontend/child-ci-analyze-flutter-web.yml
#  needs:
#    - job: unit_test_trigger
  rules:
    # Always runs after unit_test trigger
    - when: always

# analyze_flutter_mobile:
#   stage: analyze_sample_apps
#   trigger:
#     include: tools/pipelines/frontend/child-ci-analyze-flutter-mobile.yml
#  needs:
#    - job: unit_test_trigger
#   rules:
#     Always runs after unit_test trigger
#     - when: always

# Release Triggers
gitlab_github_release:
  stage: release
  trigger:
    include: tools/pipelines/backend/child-ci-release.yml
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: always
