stages:
  - unit_tests

# Firebase SDK Unit Tests
unit_tests:
  stage: unit_tests
  image: dart:stable
  script:
    - echo "Running Unit Tests..."
    - cd firebase-dart-admin-auth-sdk
    - dart pub get
    - dart analyze lib test
    - dart test --coverage=coverage --reporter expanded
  artifacts:
    paths:
      - firebase-dart-admin-auth-sdk/coverage/
    expire_in: 1d
  rules:
   - when: always
