name: Run Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read

jobs:
  release-please:
    defaults:
      run:
        working-directory: firebase-dart-admin-auth-sdk
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check current directory
        run: |
          echo "Current directory:"
          pwd
          echo "Contents:"
          ls -la

      - name: Run release-please CLI
        run: |
          npx release-please release-pr \
            --repo-url=https://github.com/aortem/firebase-dart-admin-auth-sdk \
            --token="${{ secrets.RELEASE_PLEASE_ACTION_TOKEN }}" \
            --target-branch=main \
            --config-file=release-please-config.json \
            --manifest-file=.release-please-manifest.json

      - name: Dump Release Output
        run: echo "Release process completed."
